uninstall
=> uninstall: rescue exceptions when deleting file

.travis.yml, uninstall
=> Add Travis CI configuration.

install
These seem to not apply for everyone on 10.11.0 any more (as explained in https://github.com/Homebrew/homebrew/issues/45387).
CC @DomT4 @ilovezfs @CamJN
=> install: update 10.11 /usr/local instructions.

install, uninstall
Closes Homebrew/homebrew#45692.
Closes Homebrew/homebrew#45733.
=> install/uninstall: be less cryptic on failures

install
Fixes https://github.com/Homebrew/brew/issues/667.
=> install: set CLT path if needed after install.

install
Rename and freeze them for future changes.
=> install: tweak constants.

.travis.yml, uninstall
Check if it exists first. CC @DomT4 @bfontaine 
Fixes https://github.com/Homebrew/install/issues/61
=> uninstall: handle no HOMEBREW_PREFIX/.git.

README.md
=> README: fix installation link.

install
=> install: don't fetch --prune.

.rubocop.yml, .travis.yml, install, uninstall
Add a RuboCop file based on Homebrew/brew's and fix all the failures that result.
=> Add RuboCop file and fix failures.

install
Changed as little as possible here
=> fix zsh dir permissions #72

install
Fixes https://github.com/Homebrew/brew/issues/1393
=> Always use latest CLT version (last in list).

.rubocop.yml, uninstall
=> uninstall: uninstall Caskroom.

.rubocop.yml
Ensure RuboCop is passing on 0.49.1.
=> Update RuboCop rules.

install
=> install: use https://docs.brew.sh links.

uninstall
I did not realize this would happen 🙃
=> Add message warning packages will be removed on uninstall

.travis.yml, install
And update Xcode while we're here.
=> travis.yml: update Ruby for Rubocop.

.rubocop.yml, .travis.yml
Use a newer macOS release and the system Ruby.
=> travis.yml: fix Travis CI build.

install
This should help reduce the number of issues we receive on e.g. Mojave.
=> install: tell people installing on unsupported macOS versions.

install
=> install: use fully qualified softwareupdate path

install
Let's ask people to donate when they install Homebrew.
References #4644.
=> install: solicit donations.

install
Part of https://github.com/Homebrew/brew/pull/4620.
=> install: add cask analytics message.

install
Addresses https://github.com/Homebrew/install/pull/135#issuecomment-414118207 CC @reitermarkus
=> install: also mark cask analytics message shown.

install, uninstall
Update the lists of directories that Homebrew uses, wants writable or should be removed.
=> Update Homebrew's directories

.rubocop.yml, .travis.yml, Gemfile, Gemfile.lock, install, uninstall
This allows us to actually control when the versions are upgraded.
=> travis.yml: use rubocop from bundler.

install
This is to sync up with https://github.com/Homebrew/brew/pull/4970.
=> install: create var/homebrew/linked.

.rubocop.yml, .travis.yml, install, uninstall
=> install: improve CLT installation.

README.md
We're using this as the only CI now.
=> README: use Azure Pipelines badge.

install
This will be no longer supported in Homebrew 2.0.0.
This should not be merged until 2.0.0 will be released imminently.
=> install: disable pre-Mavericks.

.rubocop.yml, Gemfile.lock, azure-pipelines.yml, install, uninstall
Mavericks ships with Ruby 2.0 so just use that by default now.
=> Use Ruby 2.0

azure-pipelines.yml
Investigate https://github.com/Homebrew/install/issues/206.
=> azure-pipelines.yml: test 10.14.

install
=> install: create .cleaned with proper ownership

install
=> Remove unused constant HOMEBREW_CORE_TAP

install
So bump minimum supported version to High Sierra.
=> install: macOS Catalina released.

install
Fixes #233 and https://github.com/Homebrew/install/pull/235#issuecomment-541607432
=> Fix command line tool installation in Catalina

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/config.yml
Add an issue template to encourage Homebrew/install issues to be better filled out.
=> Add issue template

install.sh
Port of this section: https://github.com/Linuxbrew/install/blob/2cc4266960a388510cff7325d4172e3344d7eecf/install#L449-L464
cc @sjackman
=> install.sh: print linux specific info after completion

install.sh
Port: https://github.com/Linuxbrew/install/blob/2cc4266960a388510cff7325d4172e3344d7eecf/install#L212-L217
With this change, the installer asks interactively (not on CI) where to install Homebrew (`/home/linuxbrew/.linuxbrew` with sudo or `~/.linuxbrew` without sudo).
cc @sjackman
=> install.sh: check sudo and ask for prefix

install.sh
Current output is:
```
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
https://github.com/Homebrew/brew#donations
- Install the Homebrew dependencies if you have sudo access:
Debian, Ubuntu, etc.
sudo apt-get install build-essential
Fedora, Red Hat, CentOS, etc.
sudo yum groupinstall 'Development Tools'
See https://docs.brew.sh/linux for more information.
- Configure Homebrew in your /home/linuxbrew/.profile by running
echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /home/linuxbrew/.profile
- Add Homebrew to your PATH
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
- We recommend that you install GCC by running:
brew install gcc
==> Next steps:
- Run `brew help` to get started
- Further documentation: 
https://docs.brew.sh
```
=> Move Linux Next steps after the Next steps heading

.github/workflows/tests.yml, uninstall
Basically three differences:
1. Parameterize default Homebrew path
2. GNU find vs. BSD find
3. .DS_Store not applicable in Linux
=> Add Linux uninstall support

install.sh
Check to ensure Git is installed before continuing. Abort upon failure.
=> check for Git, abort if not present

install
=> Fixed compatibility with Ruby 2.0 (macOS <= 10.12)

uninstall
This is uninstaller counterpart of #288. I believe the consistency matters here too.
=> Fix compatibility with Ruby 2.0 for the uninstaller

README.md
Direct people towards the Bash version.
=> README: update uninstall reference.

.github/workflows/tests.yml
GitHub Actions provides this now/sometimes.
=> workflows/tests: uninstall Homebrew on Linux.

install.sh, uninstall.sh
Fixes issue https://github.com/Homebrew/install/issues/313. Fixes SUDO_ASKPASS support in the install script. Copied from https://github.com/Homebrew/install/pull/306
=> Fix SUDO_ASKPASS support

install.sh, uninstall.sh
Allows the install script to be run when the user is a standard user and not part of the admin group.
Fixes #312
=> Run as a standard user

install.sh
Don't attempt to install on Linux systems with Glibc older than 2.13.
😢
=> install.sh: check Glibc version

.github/workflows/tests.yml
- fix `pull_request: []` warning
- use `@main` actions
- Remove unnecessary run name
=> GitHub Actions Cleanup

install.sh
To match the support status of Homebrew/brew.
=> install.sh: drop support for Mavericks

install.sh
=> install.sh: no_usable_ruby: restore IFS before return

install.sh
Not yet ready for merging, to be shipped as soon as Big Sur ships
See also: https://github.com/Homebrew/brew/pull/9054
=> macOS Big Sur

install.sh
Part of https://github.com/Homebrew/brew/issues/9211
=> Adjust latest supported macOS logic for e.g. Big Sur 11.1.

.github/workflows/tests.yml
- ~setup and test under WSL~ extracted to https://github.com/Homebrew/install/pull/360
- Use `/bin/bash` everywhere to ensure we're using the system Bash
- Run the install script more like how we do on the homepage
- Split up more commands so their output is more obvious
=> workflows/tests: improve CI.

.github/workflows/tests.yml
Perhaps worth waiting until https://github.com/Vampire/setup-wsl/compare/master...e314734diff-1e26d92e3b733c2c40cc73393d45d7f65f0429033c3096707cd3facdc5ca84e9
=> workflows/tests: add Windows 10 WSL support.

install.sh
This should prevent a recurrence of https://github.com/Homebrew/discussions/discussions/363#discussioncomment-246193
=> install.sh: early exit on unsupported OS

install.sh
Point to the docs and an alternate installation method.
=> install.sh: improve Homebrew on Linux ARM messaging.

install.sh
- make sure `shell_profile` is defined before use
- keep message order consistent between macOS and Linux
Fixes https://github.com/Homebrew/discussions/discussions/464.
=> install: fix next steps messaging

install.sh
=> install: use full uname path on macOS

install.sh
Several fixes:
1. On macOS, the octal format of `stat` for access rights is `%A`, but it is `%a` on Linux.
2. Do add rights for other users not in the file's groups (`o`). Command `chmod 755` will add read and execute permissions for other users not in the file's groups (`o`). For exmaple, if users set `umask 027` in their shell profile, command `mkdir newdir` will create a directory with mode 750 (rwxr-x---), but `chmod 755 newdir` will change it's mode to 755 (rwxr-xr-x).
3. Always remove write permission for groups (`g` and `o`) for zsh site-functions (fixes #549).
=> install: fix directory permissions (fixes #549)

.github/workflows/tests.yml
Fix the non-default remote URLs in CI tests.
=> tests: fix non-default URLs for test cases

.github/workflows/tests.yml, install.sh, uninstall.sh
These changes are fixed by `brew style --fix install.sh`. The new shell formater is introduced in Homebrew/brew#12044.
See Homebrew/brew#12044 for more details.
`brew style --fix install.sh` before all commits (d0833a151922ae830435cc682cc999bb1626b427@master):
<details>
<summary>Results...</summary>
<p>
```
In install.sh line 21:
if [[ "$OS" == "Linux" ]]; then
^-^ SC2250: Prefer putting braces around variable references even when not strictly required.
Did you mean: 
if [[ "${OS}" == "Linux" ]]; then
In install.sh line 23:
elif [[ "$OS" != "Darwin" ]]; then
^-^ SC2250: Prefer putting braces around variable references even when not strictly required.
Did you mean: 
elif [[ "${OS}" != "Darwin" ]]; then
In install.sh line 33:
if [[ "$UNAME_MACHINE" == "arm64" ]]; then
^------------^ SC2250: …
```
=> style: fix inconsistent code style for shell scripts

.github/workflows/tests.yml, uninstall.sh
Run `brew style *.sh` in CI test.
=> tests: check code style in CI tests

install.sh, uninstall.sh
- drop reference to IRC and match wording from diagnostic.rb
- various grammar fixes
- some formatting fixes for consistency
- ensure documentation link appears last with a blank line following
=> install.sh: wording maintenance

.github/workflows/tests.yml, install.sh, uninstall.sh
Use arrays to store command lists for commonly used commands to make them more extendable. See #581.
=> Refactor: command as array

install.sh
Fixes https://github.com/Homebrew/install/issues/625
=> install.sh: ask return or enter.

install.sh
Fixes https://github.com/Homebrew/install/issues/648
=> Move missing $USER handling to before usage

install.sh, uninstall.sh
=> ensure scripts are not run in POSIX mode

install.sh
Fixes #621 with the changes made in https://github.com/Homebrew/actions/pull/305 and https://github.com/Homebrew/brew/pull/13814.
=> install: Improve Docker detection

install, uninstall
These have been deprecated for over two years. Time to make them fail.
=> Disable deprecated scripts

install.sh
The experience in a non-default experience is very poor. Let's not encourage it.
=> install: only support default prefix on Linux.

install.sh
Companion PR to https://github.com/Homebrew/brew/pull/14021
=> install.sh: support macOS Ventura

install.sh
=> install.sh: fix "printf: - : invalid option" & format

uninstall.sh
Fixes https://github.com/Homebrew/install/issues/724
=> Support optional space after `-p` / `--path`

README.md
Made a sentence in the README more clear so it sounds better.
=> Make sentence more clear

install.sh
Reverts Homebrew/install#752
Fixes https://github.com/Homebrew/install/issues/754
=> Revert "Fix `./bin` being in `$PATH`"

README.md
This seems a nice place to let people know.
Won't be merged until we have a new Homebrew release with an installer uploaded.
=> README: document macOS .pkg installer.

install.sh
Companion PR to https://github.com/Homebrew/brew/pull/18296
=> install.sh: support macOS Sequoia

install.sh
Follow-up to https://github.com/Homebrew/install/pull/881#pullrequestreview-2328451955.
=> Use separate `echo`-es in post-install instructions

.github/ISSUE_TEMPLATE/bug.md
A bunch of our issues are basically "`git fetch` failed and I didn't read the output".
=> ISSUE_TEMPLATE/bug: add internet connection checkbox.

uninstall.sh
Addresses https://github.com/orgs/Homebrew/discussions/6033
Also check for `brew` before trying to run it.
=> linux: cleanup default Homebrew parent dir

.github/workflows/tests.yml
Part of https://github.com/Homebrew/brew/issues/17296
=> workflows/tests: use main branch.

install.sh
https://github.com/Homebrew/install/pull/990/files#r2166327521
=> install.sh: make sure Git's default branch is `main`

install.sh
`master` is still around so it will keep working but let's do things nicely here.
=> install.sh: Homebrew/core uses `main` default branch.

install.sh
Otherwise the user gets prompted for password twice.
Closes #999.
=> install.sh: do all sudo stuff before first `brew` run

install.sh
Companion to https://github.com/Homebrew/brew/pull/20681.
=> Support macOS Tahoe
