- install
Running `brew doctor` before a user runs into trouble seems to inspire anxiety uncorrelated to the magnitude of the problems encountered, which has gotten worse as `brew doctor` has gotten more verbose (and more helpful!). Telling users to run `doctor` out of the gate conflicts with the spirit of the message in the `doctor` output telling users not to worry about reports until they've actually run into trouble. I think removing this advice will help improve the new user experience.
> Don't tell new users to run brew doctor

- install
Somehow a regular space got turned into a non-breaking space.
> install: Fix stray non-breaking space

- install
We've been trying to avoid doing this for a while but it seems sensible to just do this by default considering how often we're recommending users do it.
Closes https://github.com/Homebrew/install/issues/21.
CC @Homebrew/owners
> install: chown as user.

- .travis.yml
- install
It bugged me a little there's just this one GUI interaction required to install brew on a newly installed machine. By creating the temporary file ```/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress```, you can instead use ```softwareupdate``` to download without any interaction required.
> Enable headless/non-interactive install of Command Line Tools.

- install
My proposed fix for issue #39, where the destination directories for the shell completion scripts do not have their permissions modified for user level access during the installation process, as with the other install directories.
> Added shell completion script paths to chmods/chowns/chgrps array.

- install
And avoid duplicating the message unnecessarily at the first `brew update`.
References https://github.com/Homebrew/brew/issues/142.
> Notify about analytics more explicitly.

- install
When a computer is 'managed', it won't return the local groups, but rather the organization's groups:
```
$ groups
COMPANY\Domain Users COMPANY\Document Managers COMPANY\Wireless
```
Which will cause the installer to fail, because it can't find 'admin'
```
$ ruby install
This script requires the user swalsh to be an Administrator. If this
sucks for you then you can install Homebrew in your home directory or however
you please; please refer to our homepage. If you still want to use this script
set your user to be an Administrator in System Preferences or `su' to a
non-root user with Administrator privileges.
```
The OSX-y way of doing this is 'dsmemberutil':
```
$ dsmemberutil checkmembership -U swalsh -G admin
user is a member of the group
```
> Correctly determine membership in the 'admin' group when 'group' only

- install
This PR fix issues when installer return non-valid result for valid username :).
**Sympton:**
The user jurasek cannot be found
There was an unknown error.
This script requires the user jurasek pavel to be an Administrator. If this
sucks for you then you can install Homebrew in your home directory or however
you please; please refer to our homepage. If you still want to use this script
set your user to be an Administrator in System Preferences or `su' to a
non-root user with Administrator privileges.
**Investigation**
DVG-C02RG33FG:install jurasek pavel$ echo $USER
jurasek pavel
as you can see $USER need to be skipped in installer file.
> Fix problem when user name has white space in name like 'jurasek pavel'

- install
Shouldn't be needed but never causes problems and sometimes provides fixes.
Fixes #49.
> install: always mkdir -p.

- .travis.yml
- Use only one OS X image
- Update the OS X image
- Enable email notifications to catch breakage.
> travis.yml: various tweaks.

- uninstall
`/usr/local` belongs to root by default and the Homebrew installation changes this. The post-uninstallation message omits this information.
> Replace chmod with chown in post-uninstall message

- install
This is currently just set to HOMEBREW_PREFIX but may not be in future.
Use it consistently to ensure that we don’t assume `.git` is in the HOMEBREW_PREFIX.
> Add HOMEBREW_REPOSITORY variable.

- install
This stops issues with them being created at a later point after e.g. the `/usr/local` permissions may have changed.
Also, don't make ZSH's directories group writable as ZSH complains.
> Create all root directories.

- install
This means that we can move stuff around inside the repository without causing conflicts on `update` or dumping things in `/usr/local` but keep all our existing bottles working as-is.
CC @Homebrew/maintainers for thoughts because this is a pretty big change.
> install: default repo to /usr/local/Homebrew.

- install
Handle the case where users already have stuff there before installing Homebrew.
Fixes https://github.com/Homebrew/brew/issues/945
> install: restore more group chmods.

- install
This will ensure that e.g. the symlinks and any other migrations are done even if there's no updates.
References https://github.com/Homebrew/brew/issues/1045.
> install: use update --force.

- install
Otherwise this causes the CLT to try and install which preempts our nice messaging.
> install: don't check for git early.

- install
- uninstall
A bunch of users end up in a state where they can neither install nor uninstall if their internet connection dies half way through installation. Instead let's allow the installer to be rerun and have the
uninstaller do a more thorough cleanup of our new locations and use `sudo` to do so.
> Improve based on user failures and repo migration.

- install
`--force` particularly will avoid some issues we've seen with people trying to run `install` on pre-migration Git repositories e.g. http://discourse.brew.sh/t/partial-install-cannot-continue/200
> install: tweak git fetch options.

- .travis.yml
- install
Also fixes the default core-tap installation location when installing with `curl`.
This fixes a lot of the issues in https://github.com/Homebrew/brew/issues/729#issuecomment-253278662, particularly for users trying to bootstrap Homebrew without simultaneously installing the CLT. 
cc @MikeMcQuaid 
ref Homebrew/brew/issues/729
> install: Allow painless CLT-free installation with --force-curl.

- .rubocop.yml
- install
- uninstall
This is still needed on older OS X versions at installation time.
> Fix Ruby 1.8 support.

- install
The `sudo` timestamp should only be invalidated if `sudo` was activated first inside the `install` script. If the timestamp was active before the script, it should also be left intact after the script.
> Only invalidate `sudo` if it wasn’t active before `install`.

- install
Reverts Homebrew/install#84
https://github.com/reitermarkus/install/blob/c2c00a4634b425588ee150dbb7978dd12c034c5e/install#L163 means that `stderr` output is never displayed. CC @reitermarkus 
Closes https://github.com/Homebrew/install/issues/87
> Revert "Only invalidate `sudo` if it wasn’t active before `install`."

- install
Allows running 
```
SUDO_ASKPASS="/path/to/askpass.sh" /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
> Add support for `SUDO_ASKPASS`.

- install
- uninstall
- `chmod` `bin/brew` in case it's already present and isn't writable.
- Don't assume `brew update` will print the analytics message (it won't as-of https://github.com/Homebrew/brew/pull/1575 as `HOMEBREW_NO_ANALYTICS_THIS_RUN` is set here) so print it ourselves.
- Use the shell's audible bell to nudge people to actually read this message (and give them less excuse to complain when they don't).
- Add an extra newline and bold all the analytics messaging so it's more visible in the output.
> install: tweak analytics and other fixes.

- .travis.yml
- install
If something is owned by a user but for some reason not writable then we need to make sure we fix that weirdness up.
Closes https://github.com/Homebrew/brew/issues/1556.
> install: fixup more bad permissions.

- .rubocop.yml
- .travis.yml
- install
It requires `--insecure` but if we can make it work: we may as well.
> Allow running installer on 10.5

- install
This means we can always use `git describe` to get the version accurately.
Fixes https://github.com/Homebrew/brew/issues/3187
> install: always perform full clone.

- install
I am happy to see the Xcode Command Line Tools (CLT) automatically installed but would like to see the notice before confirming installation. I think this notice is needed to be in line with the following statements from <https://docs.brew.sh/Installation.html> (<https://github.com/Homebrew/brew/blob/master/docs/Installation.md#installation>):
<blockquote>
It tells you exactly what it will do before it does it too. And you have to confirm everything it will do before it starts.
</blockquote>
I tested that this change with and without `/Library/Developer/CommandLineTools` present in my file system, using the following command:
```sh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/brodybits/install/xcode-clt-notice/install)"
```
> Add notice if Xcode CLT is to be installed

- .rubocop.yml
- install
If they aren't already installed. This means we don't tell users to immediately install it afterwards.
> install: always install Xcode CLT.

- install
Install command line tools for Xcode 10 won't create `/usr/include/` folder neither `iconv.h` file, that will make install script stuck on downloading-installing procedure on 
```
==> Installing the Command Line Tools (expect a GUI popup):
==> /usr/bin/sudo /usr/bin/xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
Failed during: /usr/bin/sudo /usr/bin/xcode-select --install
```
> fix command line tools checking on 10.14

- .travis.yml
- install
Note this isn't supported and the install script isn't designed to be edited.
Fixes #133
> install: update non-default prefix instructions.

- install
macOS 10.14 Mojave will be released on September 24th:
- Add support for Mojave.
- Drop support for El Capitan (unsupported as of August 2018)
> install: Mojave is being released

- azure-pipelines.yml
Use an old Boxen Ruby download for testing.
> azure-pipelines: test with Ruby 1.8.

- install
These will be deprecated in future so let's stop getting any new installs now.
See some related deprecations in https://github.com/Homebrew/brew/pull/5477.
> install: reject Snow Leopard and Leopard installations.

- install
https://discourse.brew.sh/t/install-error-ein-main-undefined-method-each-for-users-myusername-library-caches-homebrew-string-nomethoderror/3942
Closes https://github.com/Homebrew/install/pull/172
> install: fix bad cache reference.

- Gemfile.lock
- azure-pipelines.yml
- install
We don't want to silently ignore failing commands.
> azure-pipelines-yml: early exit on errors.

- install
This should make the Linux failure case a little nicer and SIP protects us from El Capitan onwards.
> install: use /usr/bin/ruby.

- install
This is almost always set but lets throw a better error when it is not.
> install: fail unless USER is set.

- README.md
Trivial documentation fix to use `https`.
> Fix http link in docs

- install
I actually ran into [this issue][1] on `Linuxbrew/install` when testing inside
Docker and noticed that [#201][2] had been merged in `Homebrew/install`.
This is a copy of the [PR][3] I did to `Linuxbrew/install` and I guess is a bit
more forgiving?
[1]: https://github.com/Linuxbrew/install/issues/48
[2]: https://github.com/Homebrew/install/pull/201
[3]: https://github.com/Linuxbrew/install/pull/62
> Gracefully handle missing USER env var

- install
This prevents cleanup from being run immediately after the first action on a fresh installation.
Also updated the macOS version warning message to match brew's in `diagnostic.rb`.
> install: add `.cleaned` file to cache

- install
- Only try the automated installation on >=10.13. This let's us clean up crufty code on versions we don't support anyway (that can still run the command manually).
- Fix the matching to work on Catalina
Fixes #233.
> install: tweak CLT installation

- install
- The `--local` option doesn't exist in early versions of git (~1.7),
but its behaviour is the default (saving in the current repo's .git
directory).
- As it's the default across versions, we don't need to specify it
everywhere. The `global` and `system` flags are still legitimate.
- Reported in https://github.com/Linuxbrew/install/issues/78, and we'll
merge these changes into that fork.
> Remove `--local` from `git config` commands as it's the default

- LICENSE.txt
The existing license file was close to the 2-clause BSD license, but the
text didn't match exactly. This commit overwrites this repo's
LICENSE.txt file with the one from Homebrew/brew.
Closes #246.
> Adopt LICENSE.txt from Homebrew/brew

- install
This should avoid user confusion when they see this message.
> install: make clear no analytics data is sent.

- .github/workflows/tests.yml
As @MikeMcQuaid said here: https://github.com/Homebrew/install/pull/270#issuecomment-594464647
Shellcheck has now its own step and PATH is set in a separate step too.
I also deleted the last `uninstall` line, as it seems to be not much needed?
> workflows: new shellcheck and PATH setting steps

- install.sh
These two tests must use the same command to test whether the user has sudo access to ensure consistent results.
The user may have sudo access to echo but not to mkdir. Use mkdir, because it's the first sudo command run by the installer.
> install.sh: Use sudo -l mkdir rather than sudo -v

- install.sh
This is necessary for older gits, which will only fetch the tags and not
e.g., the `master` ref.
Tested on git 1.8.3
> Separately fetch commits and tags

- install.sh
Don't execute `sudo` when creating `$HOMEBREW_CACHE`, so that if `~/.cache` (the parent directory of `$HOMEBREW_CACHE` on Linux) doesn't exist, the installer doesn't leave behind a root-owned `~/.cache`.
Closes #279.
Tested with the following Dockerfile:
```docker
FROM ubuntu:19.10
RUN apt-get update \
&& apt-get install -y \
sudo \
libc6 \
gcc \
make \
curl \
file \
git
RUN useradd --create-home user1 \
&& usermod -aG sudo user1 \
&& echo "user1 ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER user1
WORKDIR /home/user1
COPY install.sh /home/user1/install.sh
RUN /bin/bash -c "/home/user1/install.sh"
RUN ls -l -a /home/user1
```
> Don't create $HOMEBREW_CACHE with sudo on Linux

- install.sh
Fix bug introduced in b2dd833c.
I also suggest using `stty -g` to save terminal state and then restore to it.
CC @sjackman
> Fix terminal device

- .github/workflows/tests.yml
This was only needed on older versions of macOS.
> workflows/tests: remove unneeded `pkgutil --forget`.

- uninstall.sh
I see `/bin/bash: line 5: $1: unbound variable` error on aborting the uninstaller quickly.
> Fix unbound variable error on quick abort

- uninstall
This should pass down the ruby command line parameters to bash. The `man bash` docs say:
```
-c string If the -c option is present, then commands are read from string. If
there are arguments after the string, they are assigned to the positional 
parameters, starting with $0.
```
So therefore we first add parameter `$0` (which is normally then filename of the script you are invoking) and call it `uninstall` (it can ban be anything). And after that we append the command line arguments in the same order as we got them.
You can test it like so:
```sh
ruby uninstall --help
```
Or so:
```sh
ruby uninstall --dry-run --force
```
> Pass down cmd arguments to bash, fixes #299

- install.sh
In most Linux/Unix distributions, `touch` either still resides in `/bin` and is symlinked there from `/usr/bin` (e.g. Ubuntu) or has been moved to `/usr/bin`, which itself is symlinked from `/bin` (e.g. [Fedora](https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/), [Arch](https://wiki.archlinux.org/index.php/Frequently_asked_questions#Does_Arch_follow_the_Linux_Foundation's_Filesystem_Hierarchy_Standard_(FHS)?)). 
Fixes #284.
> Use /bin/touch on Linux

- install.sh
```bash
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/brew/': Failed to connect to github.com port 443: Operation timed out
Failed during: git fetch origin --force
==> Installation successful!
==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
https://docs.brew.sh/Analytics
No analytics data has been sent yet (or will be during this `install` run).
==> Homebrew is run entirely by unpaid volunteers. …
```
> exit at subshell failed

- install.sh
When using Apple Transition Kit installing Command Line Tools is not needed. 
The command line tools are Intel based, and end up breaking things.
*Note*: Brew fails to run because of some Ruby issues. I will try to fix this in another PR.
> Do not install Command Line Tools on ARM Mac

- install.sh
`uname` has potentially surprising behaviour under Rosetta: it reports the running Mac as being Intel-based. That's probably correct for many cases, where what we want to check is "is this Mac currently running Intel code". However, in the case where what we want to check for is the actual processor, it will give us the wrong results.
We don't want to install the CLT at all for Apple Silicon Macs, whether the installer is running in Rosetta or not. I've checked, and this `sysctl` check returns `1` if the physical CPU is Apple Silicon, regardless of whether or not it's in Rosetta.
The stderr redirection and `|| '0'` is because this key isn't recognized on older OSs, and therefore trying to access it would cause it to exit 1 without results in the expected format.
> Install: fix Apple Silicon detection under Rosetta

- install.sh
This change means that users should be able to see all relevant messages (analytics, donations, shellenv, etc) on one 80x24 screen on Linux.
Also checks that cURL is installed.
> install: make the postinstall message shorter

- install.sh
The current CLT delivery through `softwareupdate` is broken.
> install.sh: don't try to install CLT on Big Sur.

- install.sh
It appears to work better now (the headless part anyway).
> install.sh: restore CLT install on Big Sur

- install.sh
@jonchang, unless I'm missing something, I think we can replace `should_install_curl` and `should_install_git` with `! command -v ... >/dev/null` without any loss of functionality.
> install.sh: use fewer functions

- .github/workflows/tests.yml
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Action and workflow authors who are setting environment variables via stdout should update any usage of the set-env and add-path workflow commands to use the new environment files.
> Use GITHUB_PATH instead of add-path

- install.sh
This version doesn't mess with IFS, so it's probably more robust, and definitely easier to understand.
> Improved no_usable_ruby() test

- install.sh
Reverts Homebrew/install#338
Fixes https://github.com/Homebrew/install/issues/342
> Revert "Improved no_usable_ruby() test"

- README.md
- I came here to get the command for the uninstall script for something, and noticed that the Linux and WSL instructions were oddly separate.  Also, the `Linuxbrew` docs site page links back to the homepage for the main install command, which is circular.
- Instead, add a note for the pre-requisite packages for Linux.
> README: Make it more visible that Linux and macOS share an installer

- install.sh
Refuse to install unless on Intel processors. If we're on macOS ARM then output a custom message letting people know they can use Rosetta.
**This needs to be merged and in a tagged release before Big Sur is released so please prioritise testing and reviewing this ASAP CC @claui @Bo98 @fxcoudert @mistydemeo**
> install.sh: check processor.

- install.sh
Current version of installer prints a terse error on DTK:
Homebrew is only supported on Intel processors!
Fixes: 8f22b74e637 ("install: recommend Rosetta only on macOS")
> install: Return rosetta advice on arm64 macOS

- install.sh
We consistently try to stay under this width in the installer, so rewrap some lines to match this. (HOMEBREW_PREFIX tested with the longest prefix, `/home/linuxbrew/.linuxbrew`, which makes the line 78 chars)
> Rewrap lines to 80 character width.

- install.sh
Install script does not prompt for password for user to make choice between root and non-root install. 
If you install homebrew you can at some point hit the question 
```
Select the Homebrew installation directory
Enter your password to install to..
Press Control-D to install to ...". 
```
However, the check to prompt this is `sudo -l mkdir`. The `-l` flag is according to the sudo manpage [1] a check if the user is *allowed* to run command mkdir with sudo rights. Either the user can do this, in which case the prompt is skipped. Or the user cannot do this, in which case the prompt is shown, but useless, since the user would not be able to give useful credentials anyway.
Instead you should be using the flag `-v` which is for checking credentials and *prompting when necessary*. You can use …
> Use sudo -v instead of sudo -l mkdir

- install.sh
If you don't use `sudo`, you don't have to add -A to the arguments, even if SUDO_ASKPASS is set. 
This happens for example when you try to force a home user install with `export SUDO_ASKPASS=false`.
> Don't add -A to sudo when you don't use sudo.

- install.sh
This broke non-interactive and WSL installs.
We should not restore this behaviour until we have:
- CI that covers WSL
- CI that tests non-interactive installs
> Revert sudo changes

- install.sh
Fix a bug when `SUDO_ASKPASS` is defined but `have_sudo_access` is false.
> execute_sudo: Fix when SUDO_ASKPASS without sudo

- install.sh
This bring back in the changes of #341 but without the special check of MacOS. 
Instead check for non-interactive usage, which then in turn forces an install without having going to prompt for the password. (As done in #355.)
---
Additionally, if SUDO_ASKPASS is set in a non-interactive install, still try to make use of SUDO_ASKPASS, because
1. You can provide the password with a helper program, if you have actually still *need* to provide the password, but want to do that non-interactively.
2. But you can also make use of the `export SUDO_ASKPASS=false` trick to work and force a home folder installation.
> Use sudo -v instead of sudo -l but preserve possibility to do non-interactive installs

- install.sh
The install script currently aborts if you run it as a user via su or similar from root because it checks `$UID` instead of `$EUID` which is more accurate of the currently executing user.
This patch attempts to use the correct `$EUID` and falls back to `$UID` (this is run in bash which should always have `$EUID`).
> fixed root user pre-flight check to check $EUID

- .github/workflows/tests.yml
- uninstall.sh
`-n` is more commonly recognised as the short form of the `--dry-run`
flag. This is the case, for example, with `git` and `brew`.
> uninstall: change short dry-run flag to `-n`

- install.sh
Although we're not entirely there yet, the time for Apple Silicon support is nearing. I've had a look at the installer script to see what is needed there.
> Allow ARM on macOS

- uninstall.sh
Corrected Uninstall script for detecting location of homebrew automatically in M1 Macs.
Tried Multiple times and confirmed to be working.
> Added Default prefix for MacOS on ARM in Uninstaller script

- install.sh
Fixes https://github.com/Homebrew/brew/issues/10191.
Ok, this seems to work. At the end of the install, it should show
```
==> Next steps:
- Run `brew help` to get started
- Further documentation:
https://docs.brew.sh
- Add Homebrew to your PATH in /Users/carlocab/.zprofile:
echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/carlocab/.zprofile
eval $(/opt/homebrew/bin/brew shellenv)
```
> install.sh: show shellenv instructions on Apple M1

- install.sh
It's now deprecated and read-only.
> install.sh: remove Discourse reference.

- install.sh
If the installer is run on a system that has outdated `curl` or `git` as determined by `brew.sh`, `cmd/update.sh` will attempt to install them before `homebrew/core` is tapped with `git_init_if_necessary()`. This change has the installer pull down the tap first, allowing the automatic install of either to (potentially) succeed.
> install.sh: preload homebrew/core before brew update

- install.sh
Fixes https://github.com/Homebrew/install/issues/516
Closes https://github.com/Homebrew/install/pull/517
Does this by simply moving the part of the code that checks for whether to print out instructions for $PATH before the part of the code that prints next steps.
> Fix https://github.com/Homebrew/install/issues/516

- install.sh
Everything under `$HOMEBREW_REPOSITORY` and `$HOMEBREW_CACHE` is owned by Homebrew, so any different ownerships therein should be fixed at install time.
Addresses https://github.com/Homebrew/discussions/discussions/140#discussioncomment-313198
> install: widen chown scope

- install.sh
This is a pretty minor change: someone I work with mentioned being surprised that the Homebrew install script immediately prompted them for a password (without telling them which password) with no other information, so this just tells the user that we're testing for `sudo` and that they *may* get prompted.
> install.sh: tell the user that we're going to run sudo

- install.sh
Just a simple string change. I noticed a missing word while running a NONINTERACTIVE install without having `sudo` access.
> Update HAVE_SUDO_ACCESS check's error message for macOS

- .github/workflows/tests.yml
- README.md
- install.sh
The current install script hardcodes `HOMEBREW_{BREW,CORE}_GIT_REMOTE`. Users can only get Homebrew from GitHub during the first installation. Currently the size of `homebrew-core` repo is up to  371.09 MB. Sometimes it can be really slow during the installation process.
Only after the installation is complete, the user can change the remote of the repositories.
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
brew update
```
Currently, I hack the install script when getting Homebrew. I hope it can be officially supported.
```bash
export …
```
> Read Homebrew remote URLs from environment variables and prompt for non-default values

- README.md
- install
- uninstall
- uninstall.sh
We use `HEAD` in the install instructions on brew.sh, so we may as well
do the same here.
There are still some references to `master` in `install.sh`, but I don't
think those can be changed.
> Replace references to master with HEAD

- .github/ISSUE_TEMPLATE/config.yml
Fixing typo after `brew cask` commands were deprecated
> fix typo after brew cask deprecations

- install.sh
This mirrors the same logic we use in Homebrew/brew's `brew.sh`.
> install.sh: allow Docker etc. to run as root.

- install.sh
Concern raised from https://github.com/withfig/fig/discussions/300. Opening this as a starting point for making this instruction more clear.
> install.sh: fix ambiguous instructions for modifying PATH

- install.sh
**Changes that affect Linux only**
1. New `find_tool` function (based on old `no_usable_ruby`)
searches for the specified program in PATH.
This function automatically calls `test_${tool_name}` function that
must verify that the tool satisfies Homebrew requirements. Example:
```sh
g_tool=$(find_tool git)
c_tool=$(find_tool curl)
r_tool=$(find_tool ruby)
```
2. New `test_curl` and `test_git` functions (which are similar to `test_ruby`)
3. Rewrote `no_usable_ruby` function to take advantage of the `find_tool` function
4. Search PATH for usable cURL and Git. If identified tools are not in
`/usr/bin/`, automatically set `HOMEBREW_{GIT,CURL}_PATH` and `HOMEBREW_DEVELOPER`.
**Changes that affect both Linux and macOS**
Alter the warning message about `HOMEBREW_PREFIX/bin` not being in `PATH`
and …
> install.sh: search PATH for usable cURL/Git on Linux

- uninstall.sh
I use Homebrew on an M1 Mac, and today I noticed that the last package I used from x86_64 Homebrew was now bottled for arm64. 🎉 I found the Homebrew installer, ran `uninstall.sh --help`, and it showed me that by default it’d uninstall the Homebrew in `/usr/local`. Just what I wanted!
I then ran and hastily approved the actual uninstall — and only noticed belatedly that it was actually purging `/opt/homebrew` 😅. Fortunately I keep a `Brewfile` so getting things reinstalled wasn’t too difficult, but this PR will update `--help` to show the actual `$homebrew_prefix_default` detected by the script.
> Show actual default prefix in uninstall.sh --help

- install.sh
The availability of "/usr/bin/sudo" is not guaranteed in some container 
based environment, hence adding the check here.
> install.sh: add sudo availability check

- install.sh
Function `have_sudo_access` executes before any prompt message showing up.
> install.sh: show prompt messages before asking password

- install.sh
Remove `which` command, search executables under all entries in `PATH`. Closes #574.
BTW, `which` command shows both executable files and aliases.
```console
$ which -a python
/usr/bin/python
$ alias python='python3'
$ which -a python
python: aliased to python3
/usr/bin/python
```
We should never use `which` to find usable commands ([shellcheck SC2230](https://github.com/koalaman/shellcheck/wiki/SC2230)), use `command -v` instead. However, I do not find a `which -a` equivalent for `command -v`. This PR enumerates all entries in `PATH`.
> install.sh: remove dependency for `which` command

- install.sh
The `$STAT` variable was quoted in #577 , causing errors like:
```
/bin/bash: line 265: stat -f: command not found
/bin/bash: line 265: stat -f: command not found
/bin/bash: line 277: stat -f: command not found
/bin/bash: line 285: stat -f: command not found
/bin/bash: line 277: stat -f: command not found
/bin/bash: line 285: stat -f: command not found
```
Here, we refactor it into `$STAT_FLAG`, so that we can keep our quotes nice and safe.  Note also that it's `$STAT_FLAG` and not `$STAT_FLAGS` as a subtle reminder to only supply a single flag.
> fix: correct overzealous quoting in install.sh

- .github/workflows/tests.yml
- install.sh
- uninstall.sh
This PR allows users to call the Homebrew installer in their automation scripts without asking password.
The following command will install Homebrew to `~/.linuxbrew` in non-interactive mode rather than `/home/linuxbrew/.linuxbrew`:
```bash
NONINTERACTIVE=true HAVE_SUDO_ACCESS=false bash install.sh
```
> install.sh: fail on insufficient permissions in non-interactive mode

- install.sh
- uninstall.sh
Disable unneeded check SC2312 to let CI tests pass. See Homebrew/brew#12397
> shellcheck: disable unneeded check SC2312

- install.sh
'uname -m' returns aarch64, not arm64
ref: https://github.com/Homebrew/install/pull/518
ref: https://github.com/Homebrew/install/commit/0d46eb17cff2649ac15a0b3296c782d75218863f
> install.sh: correct detection of arm64 on Linux

- README.md
- install.sh
Changes:
1. Add variable `INTERACTIVE` for force-interactive mode. ~~The variable can be changed with a warning when both `NONINTERACTIVE` and `INTERACTIVE` are set.~~
2. Show messages when `INTERACTIVE` and/or `NONINTERACTIVE` are set. Use `ohai` when the variable is set by the user and `warn` when the variable is set by the installer.
3. Add documentation for variable `NONINTERACTIVE`. (Variable `INTERACTIVE` is not added since it is a rare use-case).
> Add force-interactive mode and document variable `NONINTERACTIVE`

- install.sh
I was looking for inspiration on how homebrew does a silent install of Command Line Tools,
and noticed that removing the placeholder is wrapped in the conditional.
In practice, I don't see how command line tools are not installed, and softwareupdate can come up empty handed, but who knows. I honestly don't know if/what consequences there are if the placeholder is left behind.
> always remove command line tools placeholder

- .github/workflows/tests.yml
Now that `git://` is disabled on GitHub: this test no longer works.
> workflows/tests: remove non-default workflows tests.

- .github/workflows/tests.yml
- install.sh
HOMEBREW_PREFIX was created using mkdir -p which respects the user
umask, even when using sudo causing the wrong permissions to be set
when installing into /home/linuxbrew.
This fixes the issue by replacing mkdir with install creating the
missing parents with the specified permissions. To make it work on
linux and macos remember to only use single letter flags.
Fixes #637
> Fix install.sh failure when the umask is not 0022

- install.sh
Currently, we display instructions about adding `brew` to `PATH` when we
are running on ARM64 or on Linux. This isn't a terrible heuristic, but
we can do better by checking whether `brew` is in `PATH` instead.
Fixes https://twitter.com/TayIorRobinson/status/1524683234956750852.
> Check for `brew` in `PATH` when displaying `PATH` instructions

- install.sh
This will be a hard requirement in Homebrew 3.5.0: https://github.com/Homebrew/brew/pull/13347
Do not merge until we have released 3.5.0.
> install.sh: require macOS El Capitan.

- README.md
- uninstall.sh
Resolve #654 
Changes :
1. Add variable `NONINTERACTIVE` for non interactive mode. If this variable set to "1", this script will be executed as non interactive mode. In other case ( ex) NONINTERACTIVE is not set or not set to 1 ), it will be executed as interactive mode.
> uninstall.sh: add variable `NONINTERACTIVE` for non-interactive mode

- uninstall.sh
if upgraded to M1 from Intel homebrew will still be installed in /usr/local and will be looked in /opt so now uninstall will look at /usr/local too if explicit path is not set
> Added /usr/local to search path for M1 system 

- uninstall.sh
These can be cleaned up by hand and `install-info` doesn't ship with some versions of Linux and macOS Ventura.
Fixes #688
Closes #699
> uninstall: remove use of `install-info`

- install.sh
Several users have set `core.symlinks = false` at global level, likely in a WSL context. This breaks Aliases, among other things.
Also ensure consistency in `git config` invocations with `brew update*`.
Ref: https://github.com/Homebrew/homebrew-core/issues/112539
> install: force symlink creation

- install.sh
- I found it a little misleading that we said "alternate installation methods" but the "ARM unsupported" docs page doesn't refer the user to those.
- I am tempted to improve this situation with an "if you know what you are doing and won't ask for help, you can install Homebrew on ARM Linux", and gate it also with `HOMEBREW_DEVELOPER` or something? Since in my experiments with Homebrew on ARM Linux I had to comment out line 555 ("`else` variously abort") to get past that message. Yet the docs say that while it may be _unsupported_ (fine), it is _possible_, which the installer currently doesn't respect.
> install.sh: Fix broken docs link for ARM Linux

- install.sh
Follow-up from https://github.com/Homebrew/brew/pull/14375.
We'll keep this around after `HOMEBREW_INSTALL_FROM_API` is default.
> install.sh: support `HOMEBREW_NO_INSTALL_FROM_API`.

- install.sh
Currently, Intel macOS installs almost certainly *don't* recommend `brew shellenv`, because `/usr/local` is in `PATH` by default.
Since `brew shellenv` is designed to be idempotent, and it sets environment variables like `INFOPATH` which can affect Homebrew operations in unexpected ways (e.g. https://github.com/Homebrew/brew/issues/14356#issuecomment-1380557154), I think `brew shellenv` should *always* be recommended.
Closes https://github.com/Homebrew/brew/issues/14362.
Also use `printf` to properly fix the "no trailing newline in profile" case.
> install.sh: always recommend `brew shellenv`

- README.md
- install.sh
Now that this is the default, tweak the logic and messaging.
Do not merge until after 4.0.0 has been tagged.
> Use HOMEBREW_INSTALL_FROM_API by default

- install
- uninstall
These have been disabled for long enough that they can be removed on Homebrew's next major/minor release.
> {,un}install: delete.

- install.sh
This is not the case when `init.defaultBranch` is set to something else, like `main`. And in that case, if `HOMEBREW_DEVELOPER` is also set, the `Homebrew/brew` repository and `homebrew/core` (if tapped) will stay on that branch instead of `master` (and won't be updated anymore since there will be no tracking information available).
Also, for consistency, replace the short option `-q` with `--quiet`, the long one.
> install.sh: ensure `master` is used for `git init`

- install.sh
Reverts Homebrew/install#747
Closes https://github.com/Homebrew/install/pull/748
> Revert "install.sh: ensure `master` is used for `git init`"

- install.sh
Same as #747, but with a better approach which should be compatible with older versions of `git`. This makes sure `git init` always creates a `master` branch.
The same is being done at
https://github.com/Homebrew/brew/blob/76b87c4a00ed636bcf59c104b85863637609b66d/Library/Homebrew/dev-cmd/tap-new.rb#L162.
---
On a side note, @MikeMcQuaid mentioned in https://github.com/Homebrew/install/pull/747#issuecomment-1441774532:
> Similarly, may want to add CI for Ubuntu 18.04.
GitHub Actions will [drop](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md) their Ubuntu 18.04 runner image this April. And, all runner images provided by GitHub Actions seem to have a very recent version of Git installed. Maybe a Docker image like `buildpack-deps:18.04` could be used? Or, …
> install.sh: override default branch config for `git init` invocations

- install.sh
Check if Homebrew is already in a user's `$PATH`. If it already is, then do not provide instructions to add it.
> Check if Homebrew path evaluation statement is already in shell profile

- install.sh
Since we're testing each `git` in `$PATH` for suitability, we might as well use the one we've approved. :)
Addresses https://github.com/orgs/Homebrew/discussions/4275.
> install: use known-good Git

- install.sh
Introduced in this commit:
https://github.com/Homebrew/install/commit/ce3f3e050e6afa4a9876a4d07fda889310dff977 @gromgit (you probably care about this)
To reproduce a failing install make sure that ./bin is in your path
```
export PATH="./bin:$PATH"
```
Then run the installer.
```
/bin/bash -c "$(curl -fsSL
https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
It will fail like this
```
==> Downloading and installing Homebrew...
/bin/bash: line 234: ./bin/git: No such file or directory
Failed during: ./bin/git -c init.defaultBranch=master init --quiet
```
Because when the installer checks for a git executable it is currently in the /usr directory.
See
https://github.com/Homebrew/install/blob/95648ef45c8d59a44fa4ab8f29cdcf17d6ec48ac/install.sh#L447
And in the /usr …
> Fix `./bin` being in `$PATH`

- install.sh
Fixes #773
In https://github.com/Homebrew/install/pull/756 I introduced the bug of changing the error message "git is too old" into "git is not installed"
I tested this pr by uninstalling git and then running
```
echo -e '#!/bin/bash\necho git version 1.8.3.1' | sudo tee /usr/local/bin/git
sudo chmod +x /usr/local/bin/git
```
Before the pr it said
```
You must install Git before installing Homebrew. See:
https://docs.brew.sh/Installation
```
Now it says
```
The version of Git that was found does not satisfy requirements for Homebrew.
Please install Git 2.7.0 or newer and add it to your PATH.
```
> Fix git outdated error saying git is not installed

- install.sh
https://github.com/Homebrew/install/pull/774 broke https://github.com/Homebrew/install/pull/756 for mac.
Thanks to @Bo98 for [reporting](https://github.com/Homebrew/install/pull/774#issuecomment-1555142496)
So my fix for the fix in the fix that fixed a bug in the previous fix had a bug. This probably introduces a new bug. Hard to tell without proper test coverage.
> Fix `./bin` being in `$PATH` (mac)

- install.sh
Adapted from `uninstall.sh`:
```console
$ ./install.sh --help
Homebrew Installer
Usage: [NONINTERACTIVE=1] [CI=1] ./install.sh [options]
-h, --help       Display this message.
NONINTERACTIVE   Install without prompting.
CI               Imply NONINTERACTIVE.
$ ./install.sh -h    
Homebrew Installer
Usage: [NONINTERACTIVE=1] [CI=1] ./install.sh [options]
-h, --help       Display this message.
NONINTERACTIVE   Install without prompting.
CI               Imply NONINTERACTIVE.
$ ./install.sh --foo
Warning: Unrecognized option: '--foo'
Homebrew Installer
Usage: [NONINTERACTIVE=1] [CI=1] ./install.sh [options]
-h, --help       Display this message.
NONINTERACTIVE   Install without prompting.
CI               Imply NONINTERACTIVE.
```
I didn't modify the README since it already mentions the only …
> doc: add `install.sh --help`. Fix #790

- install.sh
Prompt user to add `shellenv` command in their `rcfile` rather than the shell profile. The profile is only sourced by the login shell, while the `rcfile` is always sourced in an interactive session.
Resolves #808.
> install.sh: prefer placing `shellenv` command in rcfile rather than shell profile on Linux

- install.sh
This adds the correct config file for the fish shell needed to load the brew environment. Fish ends up using the `~/.config/fish/config.fish` file during startup to load environment variables and scripts most of the time. This is also used by asdf and ghcup for instance.
This was brought up in discussion here:
- https://github.com/orgs/Homebrew/discussions/4412
- https://github.com/orgs/Homebrew/discussions/4722
More info:
- https://fishshell.com/docs/current/index.html#configuration
> install: add fish post install instructions

- install.sh
Homebrew allows running as root in some environments (Docker, Kubernetes, GitHub Actions, etc). When we're root, there is no point using sudo.
So, just invoke commands directly, thus removing requirement to have a functional `sudo` command.
I personally plan to use this in [macOS containers](https://macoscontainers.org).
> Fix installation in environments where sudo is missing

- install.sh
We don't want to trip people into HOMEBREW_DEVELOPER features right away (e.g. Ruby 3).
This hack is also no longer necessary since https://github.com/Homebrew/brew/commit/77203e0760fea53ee19019527bf87a997780a0a8.
> install.sh: don't set `HOMEBREW_DEVELOPER`

- install.sh
Using customized stat in $PATH can be in conflict with standard.
> Update install.sh to use /usr/bin/stat

- README.md
Follows-up https://github.com/Homebrew/install/issues/816#issuecomment-1805291353:
> > By default it uninstalls the default Homebrew, https://github.com/Homebrew/install?tab=readme-ov-file#uninstall-homebrew suggests running it with --help though. That shows how to "cleanup Homebrew whether it is installed into /usr/local/bin or /opt/homebrew independently of the native arch"
>
> I could see an argument that some of the uninstall options could be spelled out in the README so am rescoping this issue to that goal.
Closes https://github.com/Homebrew/install/issues/816.
> README.md: Add instructions on how to uninstall from a specific prefix

- install.sh
In Fish shell, parentheses are for command substitution, so the parenthesised subshell used for `echo` grouping does not work there. Instead let's use `printf` to print the post-install instructions; it's more portable.
Fixes #880.
> install.sh: use `printf` to print post-install instructions

- install.sh
For Fedora/RHEL Linux, yum was replaced by the dnf package manager in 2015.
> move install suggestion from yum to dnf, update syntax

- install.sh
Since we write the insufficient permissions message in a heredoc, the `\"` characters are rendered as-is instead of as an escaped quote character.
Before:
```
Insufficient permissions to install Homebrew to \"/home/linuxbrew/.linuxbrew\" (the default prefix).
```
After:
```
Insufficient permissions to install Homebrew to "/home/linuxbrew/.linuxbrew" (the default prefix).
```
> Remove redundant escape characters

- install.sh
Snap upstream [refuses to relax strict security confinement](https://forum.snapcraft.io/t/classic-confinement-request-for-curl/24611/13) on curl. This breaks the install process, as at least two different reports reveal: https://github.com/Homebrew/install/issues/840 https://github.com/orgs/Homebrew/discussions/5776#discussioncomment-11427538
This patch also warns the user about this rejection, because the curl snap is quite likely the only curl installed on a user's system _and_ is otherwise recent enough to pass the version test, so it provides the necessary clarification to the next thing the user sees:
```
The version of cURL that was found does not satisfy requirements for Homebrew.
Please install cURL ${REQUIRED_CURL_VERSION} or newer and add it to your PATH.
```
> install.sh: ignore curl snap if found

- install.sh
The existing comment is wrong, the commands are not for setting up PATHs:
```
- Run these commands in your terminal to add the non-default Git remote for Homebrew/brew:
echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /Users/ruoyu/.zprofile
echo 'export HOMEBREW_BREW_GIT_REMOTE="https://example.org/brew.git"' >> /Users/ruoyu/.zprofile
export HOMEBREW_BREW_GIT_REMOTE="https://example.org/brew.git"
```
With this change, the comment is updated to reflect the correct purpose of the commands:
```
- Run these commands in your terminal to add the non-default Git remote for Homebrew/brew:
echo '# Set non-default Git remote for Homebrew/brew.' >> /Users/ruoyu/.zprofile
echo 'export HOMEBREW_BREW_GIT_REMOTE="https://example.org/brew.git"' >> /Users/ruoyu/.zprofile
export …
```
> install.sh: update comment for non-default Git remote setup

- .github/workflows/tests.yml
Tighten our use of `actions/checkout` as we do not need to retain the credentials after checkout.
> tests.yml: tighten actions/checkout

- install.sh
`warn` is defined after its usage.
Fixes #919.
> Fix error message display for unknown options

- uninstall.sh
It's a very common install prefix, so any residual files found here are likely false positives.
Followup to #923.
> uninstall.sh: don't check /usr/local for residual files

- .github/workflows/tests.yml
- .github/wsl-init.yml
These changes mean that WSL setup time in CI should now be ~1200-1300% faster.
And also simplifies the long series of commands needed to set it up.
> workflows/tests: simplify WSL handling by using windows-2025

- install.sh
Since this is the most fragile part of the process for most users, might as well put in additional effort.
Tested with this `git` shim:
```bash
#!/usr/bin/env bash
realgit=/usr/bin/git
if [[ -s ~/.rand_thres ]]; then
limit=$(<~/.rand_fail)
else
limit=23456  # around 72%
fi
for i in "$@"; do
if [[ $i == "fetch" ]]; then
[[ $RANDOM -le $limit ]] && {
echo "RANDOM FATAL ERROR" >&2
exit 1
}
fi
done
exec "$realgit" "$@"
```
> install: retry git fetch on failure

- install.sh
Add support for a `/etc/homebrew/brew.no_install` file that can be used to prevent running the Homebrew installation script and optionally provide a message to the user.
> install.sh: check for file that prevents Homebrew installation.

- install.sh
- uninstall.sh
This is automatic for `/usr/local/bin/brew` but let's do it manually for other prefixes too.
See also https://github.com/Homebrew/brew/pull/20159 and https://github.com/Homebrew/install/issues/986
> Add Homebrew to PATH automatically if possible.

- install.sh
If a user has `column.ui` set to `always`, the Homebrew installation script fails. This PR fixes that by guaranteeing a non-columnar layout when parsing tags.
> Prevent git column.ui configuration from affecting install script

- install.sh
This is #286 but applied to macOS too. I believe that the same reasons apply: if in some rare cases `~/Library/Caches` or even `~/Library` doesn't exist, we don't want to create it with sudo permissions because it will then be owned by root.
Fixes #1024.
> install.sh: don't create $HOMEBREW_CACHE with sudo
